name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.7.10
        with:
          install-command: yarn --frozen-lockfile

      - name: Check Typescript syntax
        run: yarn tsc:check

      - name: Check ESLint
        run: yarn lint:check

      - name: Check Prettier
        run: yarn prettier:check
